// Combines the stylesheet modules in css/src/ into the single css/style.css
// that pages load. Modules are joined in filename order, which is also the
// cascade order, so later files can override earlier ones.
//   node scripts/build-css.cjs          write css/style.css
//   node scripts/build-css.cjs --check  exit 1 if css/style.css is out of date
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const sourceDir = path.join(root, 'css', 'src');
const output = path.join(root, 'css', 'style.css');

const header = `/* Generated by scripts/build-css.cjs from css/src/. Do not edit this file;
   edit the modules in css/src/ and run \`npm run build\`. */
`;

function render() {
  const modules = fs.readdirSync(sourceDir).filter(name => name.endsWith('.css')).sort();
  const parts = modules.map(name => {
    const css = fs.readFileSync(path.join(sourceDir, name), 'utf8').replace(/\r\n/g, '\n').trim();
    return `/* --- css/src/${name} --- */\n${css}\n`;
  });
  return header + '\n' + parts.join('\n');
}

function isCurrent() {
  return fs.existsSync(output) && fs.readFileSync(output, 'utf8').replace(/\r\n/g, '\n') === render();
}

if (require.main === module) {
  if (process.argv.includes('--check')) {
    if (!isCurrent()) {
      console.error('css/style.css is out of date (run npm run build).');
      process.exit(1);
    }
    console.log('css/style.css matches css/src/.');
  } else {
    fs.writeFileSync(output, render());
    console.log('Wrote css/style.css.');
  }
}

module.exports = { render, isCurrent };
